name: conda_toil
channels:
- defaults
dependencies:
- certifi=2016.2.28=py27_0
- libgcc=5.2.0=0
- nodejs=6.10.3=0
- openssl=1.0.2l=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=36.4.0=py27_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - avro==1.8.1
  - backports.functools-lru-cache==1.5
  - backports.ssl-match-hostname==3.5.0.1
  - cachecontrol==0.11.7
  - chardet==3.0.4
  - click==7.0
  - colormath==3.0.0
  - cwltool==1.0.20180518123035
  - cycler==0.10.0
  - decorator==4.3.0
  - dill==0.2.7.1
  - docker==2.5.1
  - docker-pycreds==0.4.0
  - docutils==0.14
  - et-xmlfile==1.0.1
  - future==0.17.1
  - galaxy-lib==17.9.3
  - idna==2.6
  - ipaddress==1.0.22
  - isodate==0.6.0
  - jdcal==1.4
  - jinja2==2.10
  - kiwisolver==1.0.1
  - lml==0.0.7
  - lockfile==0.12.2
  - lzstring==1.0.4
  - markdown==3.0.1
  - markupsafe==1.1.0
  - matplotlib==2.2.3
  - mistune==0.8.4
  - multiqc==1.7
  - networkx==2.2
  - numpy==1.15.4
  - odfpy==1.3.5
  - openpyxl==2.5.12
  - pathlib2==2.3.2
  - pyexcel==0.5.10
  - pyexcel-io==0.5.11
  - pyexcel-ods==0.5.4
  - pyexcel-xls==0.5.8
  - pyexcel-xlsx==0.5.6
  - pyparsing==2.3.0
  - python-dateutil==2.7.5
  - pytz==2018.7
  - pyyaml==3.13
  - rdflib==4.2.2
  - rdflib-jsonld==0.4.0
  - requests==2.18.4
  - ruamel.ordereddict==0.4.13
  - ruamel.yaml==0.14.12
  - scandir==1.9.0
  - schema-salad==2.7.20181126142424
  - shellescape==3.4.1
  - simplejson==3.16.0
  - six==1.11.0
  - spectra==0.0.11
  - subprocess32==3.5.2
  - texttable==1.5.0
  - toil==3.17.0
  - typing==3.6.6
  - typing-extensions==3.6.6
  - unidecode==1.0.23
  - urllib3==1.22
  - websocket-client==0.54.0
  - xlrd==1.2.0
  - xlwt==1.3.0

